name: Trigger e2e UI tests

on: push

jobs:
  chrome:
    runs-on: ubuntu-latest
    name: trigger in chrome
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-actions@v5
        with:
          browser: chrome